# This is a basic workflow to help you get started with Actions

name: Auto-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
  pull_request:
    branches: [ "master" ]
#  schedule:
#    - cron: '00 5 * * 6' # every Sunday at 5:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # reusable workflow
  get-latest-url:
    runs-on: ubuntu-latest
    steps:
      - name: get latest url
        run: |
          BASE_URL="https://www.softether-download.com"
          LATEST_FOLDER=$( curl -s $BASE_URL/files/softether/ | tr ';' '\n' | grep -i href | awk -F'"' '{ print $2 }' | sort -n | tail -n1 )
          echo "Latest folder is $LATEST_FOLDER"
          for FOLDER_STRING in "Intel_x64_or_AMD64" "ARM_64bit"
          do
            LATEST=$( curl -s "$BASE_URL/$LATEST_FOLDER/Linux/SoftEther_VPN_Server/64bit_-_$FOLDER_STRING/" | tr '<' '\n' | grep -i href | grep -i tar.gz | awk -F '"' '{ print $2 }' ) 
            echo -e "\nURL for $FOLDER_STRING: " 
            echo "$BASE_URL/$LATEST" | tee latest_url-$FOLDER_STRING.txt
          done